name: nakamas_chat
description: A chat for the lads!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  flutter_svg: ^1.1.6
  http: ^0.13.5
#  intl: ^0.18.0
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  logger: ^1.1.0
  font_awesome_flutter: ^10.3.0
  fluttertoast: ^8.1.2
  easy_localization: ^3.0.1 # flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart #flutter pub run easy_localization:generate -S "assets/translations" -O "lib/utils/keys" -o "locale_keys.g.dart" -f keys
  timezone: ^0.9.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  path_provider: ^2.0.11
  moor_inspector: ^0.3.1
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  sqlite3_flutter_libs: ^0.5.12
  flutter_local_notifications: ^13.0.0
  google_fonts: ^3.0.1
  connectivity_plus: ^3.0.2
  json_serializable: ^6.5.4
  flutter_native_splash: ^2.2.16
  json_annotation: ^4.7.0
  encrypt: ^5.0.1
  device_info_plus: ^8.0.0
  flutter_local_notifications_platform_interface: ^6.0.0
  drift: ^2.3.0
  permission_handler: ^10.2.0
  convert: ^3.1.1
  percent_indicator: ^4.2.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  google_sign_in: ^5.4.2
  bloc: ^8.1.0
  cloud_firestore: ^4.3.0
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  drift_dev: ^2.3.3
  build_runner: ^2.3.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/translations/
